name: lucide_icons
description: A Lucide icon library package for Flutter applications. Fork of Feather Icons, open for anyone to contribute icons.
version: 0.144.0
homepage: https://lucide.dev
repository: https://github.com/lucide-icons/lucide

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  html: ^0.15.0
  recase: ^4.0.0
  lint: ^1.5.3

flutter:
  fonts:
    - family: Lucide
      fonts:
        - asset: assets/lucide.ttf
